server:
  port: 8000
spring:
  application:
    name: alliance-register
  security:
    user:
      name: admin
      password: admin123
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetchRegistry: false
    service-url:
      defaultZone:  http://${eureka.instance.hostname}:${server.port}/eureka
